/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {

  writeupsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

export default sidebars;
